//go:build ignore

// Package main generates the component reference pages under
// docs/components/ from the registry's builtin ComponentSpec manifests.
// Run from the repository root:
//
//	go run docs/generate/main.go
//
// Output is deterministic; regeneration must leave a clean git diff.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/plexusone/uiforge/registry"
)

type propsSchema struct {
	Required   []string              `json:"required"`
	Properties map[string]propsField `json:"properties"`
}

type propsField struct {
	Type string `json:"type"`
	Enum []any  `json:"enum"`
}

var namespaceTitles = map[string]string{
	"core":        "Core Components",
	"analytics":   "Analytics Components",
	"application": "Application Components",
	"assistant":   "Assistant Components",
}

var namespaceOrder = []string{"core", "analytics", "application", "assistant"}

func main() {
	r, err := registry.NewWithBuiltins()
	if err != nil {
		fmt.Fprintf(os.Stderr, "load builtins: %v\n", err)
		os.Exit(1)
	}

	byNamespace := map[string][]*registry.ComponentSpec{}
	for _, spec := range r.List() {
		byNamespace[spec.Namespace] = append(byNamespace[spec.Namespace], spec)
	}
	for _, specs := range byNamespace {
		sort.Slice(specs, func(i, j int) bool { return specs[i].ID < specs[j].ID })
	}

	outDir := "docs/components"
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	var index strings.Builder
	index.WriteString(header())
	index.WriteString("# Component Reference\n\n")
	index.WriteString("Every UIForge component is described by a machine-readable `ComponentSpec` manifest in the registry. ")
	index.WriteString("These pages are generated from those manifests — the registry is the source of truth.\n\n")
	index.WriteString("| Namespace | Components | Profile affinity |\n|---|---|---|\n")

	profileNotes := map[string]string{
		"core":        "all profiles",
		"analytics":   "dashboard, application, portal",
		"application": "application, portal",
		"assistant":   "agent",
	}

	for _, ns := range namespaceOrder {
		specs := byNamespace[ns]
		if len(specs) == 0 {
			continue
		}
		ids := make([]string, 0, len(specs))
		for _, s := range specs {
			ids = append(ids, fmt.Sprintf("`%s`", s.ID))
		}
		fmt.Fprintf(&index, "| [%s](%s.md) | %s | %s |\n",
			namespaceTitles[ns], ns, strings.Join(ids, ", "), profileNotes[ns])

		page := renderNamespacePage(ns, specs)
		if err := os.WriteFile(filepath.Join(outDir, ns+".md"), []byte(page), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", ns, err)
			os.Exit(1)
		}
		fmt.Printf("Wrote %s\n", filepath.Join(outDir, ns+".md"))
	}

	if err := os.WriteFile(filepath.Join(outDir, "index.md"), []byte(index.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write index: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Wrote %s\n", filepath.Join(outDir, "index.md"))
}

func header() string {
	return "<!-- Generated by docs/generate/main.go from registry manifests. Do not edit by hand. -->\n\n"
}

func renderNamespacePage(ns string, specs []*registry.ComponentSpec) string {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, "# %s\n\n", namespaceTitles[ns])

	for _, spec := range specs {
		fmt.Fprintf(&b, "## `%s`\n\n", spec.ID)
		fmt.Fprintf(&b, "**Version:** %s · **Category:** %s\n\n", spec.Version, spec.Category)

		writeProperties(&b, spec)
		writeDataInputs(&b, spec)
		writeEvents(&b, spec)

		if len(spec.Actions) > 0 {
			fmt.Fprintf(&b, "**Actions:** `%s`\n\n", strings.Join(spec.Actions, "`, `"))
		}
		if lc := spec.LayoutConstraints; lc != nil {
			var parts []string
			if lc.MinWidth != "" {
				parts = append(parts, "min width "+lc.MinWidth)
			}
			if lc.MinHeight != "" {
				parts = append(parts, "min height "+lc.MinHeight)
			}
			if lc.MaxWidth != "" {
				parts = append(parts, "max width "+lc.MaxWidth)
			}
			if lc.MaxHeight != "" {
				parts = append(parts, "max height "+lc.MaxHeight)
			}
			if len(lc.AllowedIn) > 0 {
				parts = append(parts, "allowed in "+strings.Join(lc.AllowedIn, ", "))
			}
			if len(parts) > 0 {
				fmt.Fprintf(&b, "**Layout constraints:** %s\n\n", strings.Join(parts, "; "))
			}
		}
		if ds := spec.DesignSystem; ds != nil {
			if len(ds.Tokens) > 0 {
				fmt.Fprintf(&b, "**Design tokens:** `%s`\n\n", strings.Join(ds.Tokens, "`, `"))
			}
			if len(ds.Variants) > 0 {
				fmt.Fprintf(&b, "**Variants:** `%s`\n\n", strings.Join(ds.Variants, "`, `"))
			}
		}
	}
	return b.String()
}

func writeProperties(b *strings.Builder, spec *registry.ComponentSpec) {
	if len(spec.PropertiesSchema) == 0 {
		return
	}
	var ps propsSchema
	if err := json.Unmarshal(spec.PropertiesSchema, &ps); err != nil || len(ps.Properties) == 0 {
		return
	}
	required := map[string]bool{}
	for _, r := range ps.Required {
		required[r] = true
	}
	names := make([]string, 0, len(ps.Properties))
	for name := range ps.Properties {
		names = append(names, name)
	}
	sort.Strings(names)

	b.WriteString("| Property | Type | Required | Allowed values |\n|---|---|---|---|\n")
	for _, name := range names {
		f := ps.Properties[name]
		req := ""
		if required[name] {
			req = "yes"
		}
		enum := ""
		if len(f.Enum) > 0 {
			vals := make([]string, 0, len(f.Enum))
			for _, e := range f.Enum {
				vals = append(vals, fmt.Sprintf("`%v`", e))
			}
			enum = strings.Join(vals, ", ")
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", name, f.Type, req, enum)
	}
	b.WriteString("\n")
}

func writeDataInputs(b *strings.Builder, spec *registry.ComponentSpec) {
	if len(spec.DataInputs) == 0 {
		return
	}
	names := make([]string, 0, len(spec.DataInputs))
	for name := range spec.DataInputs {
		names = append(names, name)
	}
	sort.Strings(names)

	b.WriteString("**Data inputs**\n\n| Input | Type | Required | Description |\n|---|---|---|---|\n")
	for _, name := range names {
		in := spec.DataInputs[name]
		req := ""
		if in.Required {
			req = "yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", name, in.Type, req, in.Description)
	}
	b.WriteString("\n")
}

func writeEvents(b *strings.Builder, spec *registry.ComponentSpec) {
	if len(spec.Events) == 0 {
		return
	}
	names := make([]string, 0, len(spec.Events))
	for name := range spec.Events {
		names = append(names, name)
	}
	sort.Strings(names)

	b.WriteString("**Events**\n\n| Event | Description |\n|---|---|\n")
	for _, name := range names {
		fmt.Fprintf(b, "| `%s` | %s |\n", name, spec.Events[name].Description)
	}
	b.WriteString("\n")
}
