name: TypeScript Lint
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - 'spec/**'
      - 'renderers/**'
      - '.github/workflows/ts-lint.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'spec/**'
      - 'renderers/**'
      - '.github/workflows/ts-lint.yaml'
  workflow_dispatch:

jobs:
  spec:
    uses: plexusone/.github/.github/workflows/ts-lint.yaml@main
    with:
      working-directory: spec
  renderer-react:
    uses: plexusone/.github/.github/workflows/ts-lint.yaml@main
    with:
      working-directory: renderers/react
  renderer-lit:
    uses: plexusone/.github/.github/workflows/ts-lint.yaml@main
    with:
      working-directory: renderers/lit
